pins = [
    # Male Shirts
    {
        "src": "https://i.pinimg.com/originals/4c/6e/a8/4c6ea85bec9a25c43b159af08d4361cb.jpg",
        "alt": "Men's Regular-Fit Short-Sleeve Pocket Oxford Shirt",
        "title": "Regular-Fit Oxford Shirt",
        "gender": "Male",
        "category": "Shirts",
    },
    {
        "src": "https://i.pinimg.com/474x/fc/a4/41/fca4412b3e955ab04a1b159df422b9dc.jpg",
        "alt": "Men's half shirt | Half shirt | Men's half shirt colourful",
        "title": "Half Shirt",
        "gender": "Male",
        "category": "Shirts",
    },
    {
        "src": "https://i.pinimg.com/originals/11/5e/00/115e00ba95170fb252db310d725567a5.jpg",
        "alt": "Men's linen shirts are perfectly weight for the warmer months",
        "title": "Linen Shirt",
        "gender": "Male",
        "category": "Shirts",
    },
    {
        "src": "https://i.pinimg.com/originals/dd/de/14/ddde149b1134c4387cd174a99b8d2e31.jpg",
        "alt": "This contains an image of:",
        "title": "",
        "gender": "Male",
        "category": "Shirts",
    },
    {
        "src": "https://i.pinimg.com/474x/78/55/dc/7855dc1d49168837fa9d4911b509a6ef.jpg",
        "alt": "This contains an image of:",
        "title": "",
        "gender": "Male",
        "category": "Shirts",
    },
    {
        "src": "https://i.pinimg.com/originals/1c/1d/7f/1c1d7f67ba4595cfc242935ddb88a3a6.jpg",
        "alt": "Casual collared short sleeve shirt - cotton/linen blend",
        "title": "Green Cuban Collar Shirt",
        "gender": "Male",
        "category": "Shirts",
    },
    {
        "src": "https://i.pinimg.com/originals/52/9d/04/529d04bc97dbed06345f403ecc18d09c.jpg",
        "alt": "Basic style shirt - 95% polyester, 5% elastane",
        "title": "Black T-Shirt",
        "gender": "Male",
        "category": "Shirts",
    },
    {
        "src": "https://i.pinimg.com/originals/8e/48/96/8e4896b96e905373bc89eb303c4732a8.jpg",
        "alt": "Timeless elegance in linen - perfect attire for spring and summer",
        "title": "Linen Shirt",
        "gender": "Male",
        "category": "Shirts",
    },
    {
        "src": "https://i.pinimg.com/originals/29/bb/b1/29bbb141df9d5dfec1dace9e1b94a51f.jpg",
        "alt": "This contains an image of:",
        "title": "",
        "gender": "Male",
        "category": "Shirts",
    },
    # Female Dresses
    {
        "src": "https://i.pinimg.com/originals/4f/ad/07/4fad07c702adec0192dcd87ab039de7a.jpg",
        "alt": "Julie Silk Blouse - timeless cuts of the 1950s",
        "title": "Julie Silk Blouse",
        "gender": "Female",
        "category": "Dresses",
    },
    {
        "src": "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=400&q=80",
        "alt": "Woman in floral dress",
        "title": "Floral Dress",
        "gender": "Female",
        "category": "Dresses",
    },
    {
        "src": "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?auto=format&fit=crop&w=400&q=80",
        "alt": "Woman in white dress",
        "title": "White Dress",
        "gender": "Female",
        "category": "Dresses",
    },
    {
        "src": "https://i.pinimg.com/474x/14/15/7d/14157db2a1e4786d84c0baadc2a34112.jpg",
        "alt": "",
        "title": "",
        "gender": "Female",
        "category": "Dresses",
    },
    {
        "src": "https://i.pinimg.com/736x/a8/09/bf/a809bf17e70eecd4a34ab49f4961cb43.jpg",
        "alt": "Vintage Elegant Print Floral Dress",
        "title": "Vintage Floral Dress",
        "gender": "Female",
        "category": "Dresses",
    },
    {
        "src": "https://i.pinimg.com/originals/ab/f8/ce/abf8cec292f6cf2e9ece06ea6f866925.jpg",
        "alt": "Women's 1950s Vintage Dress",
        "title": "1950s Vintage Dress",
        "gender": "Female",
        "category": "Dresses",
    },
    {
        "src": "https://i.pinimg.com/originals/5f/52/57/5f5257408f798f0938fada0c69751094.jpg",
        "alt": "Emoji Dress",
        "title": "Emoji Dress",
        "gender": "Female",
        "category": "Dresses",
    },
    {
        "src": "https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&w=400&q=80",
        "alt": "Woman in blue dress",
        "title": "Blue Dress",
        "gender": "Female",
        "category": "Dresses",
    },
    {
        "src": "https://i.pinimg.com/originals/9d/e7/73/9de7736407bcfd1f298770b431790fad.jpg",
        "alt": "Hulianfu Chiffon Dress",
        "title": "Chiffon Dress",
        "gender": "Female",
        "category": "Dresses",
    },
    {
        "src": "https://i.pinimg.com/736x/14/cb/01/14cb0193f164b4d556fc480fe8de017b.jpg",
        "alt": "Unlocking Elegance",
        "title": "Elegant Dress",
        "gender": "Female",
        "category": "Dresses",
    },
    # Female Skirts
    {
        "src": "https://i.pinimg.com/originals/58/b0/5e/58b05e9ff077a136a2c369d3e9dfbaf5.jpg",
        "alt": "Retro Plaid Midi Wool Skirt - timeless A-line silhouette",
        "title": "Santal 3 | Retro Plaid Midi Wool Skirt",
        "gender": "Female",
        "category": "Skirts",
    },
    {
        "src": "https://i.pinimg.com/originals/47/48/76/47487679ee24578aef85feb97cb7b52a.png",
        "alt": "Scarlet Darkness Maxi Long Skirts for Women Summer Flowy Renaissance Skirt with Pockets",
        "title": "Maxi Long Skirt",
        "gender": "Female",
        "category": "Skirts",
    },
    {
        "src": "https://i.pinimg.com/originals/6b/d9/26/6bd926c4d26ea17d45b901cefd74c984.jpg",
        "alt": "Plaid wool skirt",
        "title": "Plaid Wool Skirt",
        "gender": "Female",
        "category": "Skirts",
    },
    # Male Jackets
    {
        "src": "https://i.pinimg.com/originals/36/84/cd/3684cdb6c819f360486e0b1b489167a0.jpg",
        "alt": "Men's Varsity Jacket School Uniforms",
        "title": "Varsity Jacket",
        "gender": "Male",
        "category": "Jackets",
    },
    {
        "src": "https://i.pinimg.com/originals/f7/d7/30/f7d7300285c96b96c5bf4cd6202a7a49.jpg",
        "alt": "Style: Casual, Neckline: Hooded, Fit Type: Regular Fit",
        "title": "Hooded Coat",
        "gender": "Male",
        "category": "Jackets",
    },
    {
        "src": "https://i.pinimg.com/originals/a0/ed/cc/a0edccbf676a1336d8b87ff007dc716b.jpg",
        "alt": "Material: Polyester, Length: Regular, Sleeve Length: Long Sleeve",
        "title": "Letter Print Jacket",
        "gender": "Male",
        "category": "Jackets",
    },
    {
        "src": "https://i.pinimg.com/originals/62/b1/91/62b191aa793e91581b3ac6ef3b2d9a1a.jpg",
        "alt": "Suit Set",
        "title": "Suit Set",
        "gender": "Male",
        "category": "Jackets",
    },
    {
        "src": "https://i.pinimg.com/originals/8f/b3/8f/8fb38f284775ae6b71b678943811cecc.jpg",
        "alt": "This contains an image of:",
        "title": "",
        "gender": "Male",
        "category": "Jackets",
    },
    {
        "src": "https://i.pinimg.com/originals/1a/e9/c9/1ae9c940491fe431813e4ce66a7b4976.jpg",
        "alt": "Classy Meets Contemporary 21 Stylish Suits Every Modern Man Needs",
        "title": "Contemporary Suits",
        "gender": "Male",
        "category": "Jackets",
    },
    {
        "src": "https://i.pinimg.com/originals/8b/de/4d/8bde4db05c914e7111eb95b8dbe8174e.jpg",
        "alt": "This contains an image of:",
        "title": "ZIOZIA Jacket",
        "gender": "Male",
        "category": "Jackets",
    },
    # Female Jackets
    {
        "src": "https://images.unsplash.com/photo-1515378791036-0648a3ef77b2?auto=format&fit=crop&w=400&q=80",
        "alt": "Woman in stylish jacket",
        "title": "Stylish Jacket",
        "gender": "Female",
        "category": "Jackets",
    },
    {
        "src": "https://images.unsplash.com/photo-1555620366-c4c9d9cbb8e8?q=80&w=1972&auto=format&fit=crop&w=400&q=80",
        "alt": "Woman in coat dress",
        "title": "Coat Dress",
        "gender": "Female",
        "category": "Jackets",
    },
    # Styles & Casual Looks
    {
        "src": "https://i.pinimg.com/originals/cb/d1/0c/cbd10c35a50e018aff64499d9c25d2fc.jpg",
        "alt": "",
        "title": "",
        "gender": None,
        "category": "Styles",
    },
    {
        "src": "https://i.pinimg.com/originals/78/af/5d/78af5ddc996ed1df4c318cd4e64b2a82.webp",
        "alt": "From Office to Wedding: 13 Essential Smart Casual Looks for Men",
        "title": "Smart Casual Looks for Men",
        "gender": "Male",
        "category": "Casual Looks",
    },
]
